eureka:
  instance:
    prefer-ip-adderess: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka:password@localhost:8761/eureka}
